# Generated by Django 4.0.4 on 2022-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_product',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
