# Generated by Django 4.0.4 on 2022-04-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_date_product_date_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_product',
        ),
    ]
